### ISSUE TITLE
Get lua exception line number during call_python

### ISSUE THREAD

**Issue by WillPangZi** [scoder/lupa#110]
Hi, really awesome project, very help for dynamic third party lua script.
When I execute long lua script, and during call_python function, we encounter a python exception like below.
My question is can i get on which Lua line we called python method and cause excepiton.
Or anyway to get last line runned in Lua when I catch the exception.

Thanks.
 
`
[2019-04-13 17:36:42] [ERROR] Traceback (most recent call last):
  File "/Users/pangzi/PycharmProjects/TaskConsole/Modules.py", line 83, in action
    self.lua.execute(luaContent);

  File "lupa/_lupa.pyx", line 280, in lupa._lupa.LuaRuntime.execute

  File "lupa/_lupa.pyx", line 1297, in lupa._lupa.run_lua

  File "lupa/_lupa.pyx", line 1306, in lupa._lupa.call_lua

  File "lupa/_lupa.pyx", line 1331, in lupa._lupa.execute_lua_call

  File "lupa/_lupa.pyx", line 253, in lupa._lupa.LuaRuntime.reraise_on_exception

  File "lupa/_lupa.pyx", line 1469, in lupa._lupa.py_call_with_gil

  File "lupa/_lupa.pyx", line 1456, in lupa._lupa.call_python
  File "/Users/pangzi/PycharmProjects/TaskConsole/zservice/__init__.py", line 257, in click
    self.d(**table).click();
  File "/Users/pangzi/PycharmProjects/TaskConsole/uiautomator/__init__.py", line 79, in __call__
    return self.func(*args, **kwargs)
  File "/Users/pangzi/PycharmProjects/TaskConsole/uiautomator/__init__.py", line 1240, in _click
    return self.jsonrpc.click(self.selector)
  File "/Users/pangzi/PycharmProjects/TaskConsole/uiautomator/__init__.py", line 524, in wrapper
    return _method_obj(*args, **kwargs)
  File "/Users/pangzi/PycharmProjects/TaskConsole/uiautomator/__init__.py", line 170, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.TextView0, INDEX=1]`

**Comment by scoder** [comment]
I wouldn't mind having this as a feature. Cython emulates Python frames for its own C code, so it's possible to do this, although Cython does not make its implementation available to user code (currently). It's probably not all that difficult to generate one or more fake frame objects in `reraise_on_exception()` that refer to the Lua code line/s (assuming that can be fetched from the Lua exception somehow).

A PR for that is welcome. You can look at the `__Pyx_AddTraceback()` function in `_lupa.c`.

**Comment by WillPangZi** [comment]
Thanks, will try to add the PR.
Seems need lots time, as C code is difficult for python user...

**Comment by scoder** [comment]
Somewhat luckily then, you don't have to write C code yourself, since Lupa is written in Cython (which generates the C code). But yes, it's not trivial and requires a bit of understanding of the CPython C-API.

The more important part, though, is to figure out how to extract the stack trace information from Lua. Once that's clear, we can see how to present it in Lupa.

**Comment by WillPangZi** [comment]
Tested a lot, didn't find a solution to throw lua stacktrace in _lupa.pyx.
But found a workaround to get the stack trace.

the workaround is:
Catch exception in Python, and raise lua exception in python.
`
def pyfun(ssss):
    try:
        raise "pyfun exception"
    except:
        lua.eval('error("find Exception in python function")')
`
