### ISSUE TITLE
Odd Error

### ISSUE THREAD

**Issue by SoulSen** [scoder/lupa#130]
I keep getting the error 
```
Traceback (most recent call last):
  File "C:\Users\taluk\Documents\Coding Projects\Python\Musix\utils\environment\lua\Environment.py", line 38, in execute_lua
    ret = self.dev_lua.execute(code)
  File "lupa\_lupa.pyx", line 280, in lupa._lupa.LuaRuntime.execute
  File "lupa\_lupa.pyx", line 1297, in lupa._lupa.run_lua
  File "lupa\_lupa.pyx", line 1306, in lupa._lupa.call_lua
  File "lupa\_lupa.pyx", line 1331, in lupa._lupa.execute_lua_call
  File "lupa\_lupa.pyx", line 253, in lupa._lupa.LuaRuntime.reraise_on_exception
  File "lupa\_lupa.pyx", line 1576, in lupa._lupa.py_object_getindex_with_gil
  File "lupa\_lupa.pyx", line 1552, in lupa._lupa.getattr_for_lua
TypeError: attribute name must be string, not 'NoneType'
```

I invoke my lua code here 

```py
  def execute_lua(self, code, ctx=None, safe=True):
        self.lua.globals()['ctx'] = ctx

        try:
            start = time.time()
            if safe:
                self.bot.lua_dev_ctx = ctx
                print(code)
                ret = self.dev_lua.execute(code)
                print('right?')
                self.bot.lua_dev_ctx = None
            else:
                ret = self.lua.execute(code)
        except Exception as e:
            end = time.time()
            interval = end - start
            self._recreate_stdout(safe)
            traceback.print_exc()
            return e.with_traceback(e.__traceback__), interval, False
        else:
            end = time.time()
            interval = end - start
            value = self.lua_stdout.getvalue() or 'None'
            self._recreate_stdout(safe)

            return value or ret, interval, True
```

And this is the code I'm trying to run
```lua
bot.is_ready()
```

I have tried this with all functions of this object, though it seems to give me the same error. The global `bot` is an instance of an object that's already instantiated. It seems though I don't get this error when trying to access normal attributes.

**Comment by SoulSen** [comment]
Nevermind, I have found the problem, this is not Lupa's fault.
