### ISSUE TITLE
Absolute path appears in SOURCES.txt of sdist

### ISSUE THREAD

**Issue by uekd** [scoder/lupa#194]
Im new can someone help
```
Microsoft (R) Library Manager Version 14.28.29915.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

    running build_ext
    building 'lupa._lupa' extension
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\Users
    creating build\temp.win-amd64-3.9\Release\Users\HP
    creating build\temp.win-amd64-3.9\Release\Users\john\AppData
    creating build\temp.win-amd64-3.9\Release\Users\john\AppData\Local
    creating build\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp
    creating build\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j
    creating build\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c
    creating build\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCYTHON_CLINE_IN_TRACEBACK=0 -IC:\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\third-party\lua -Ic:\users\john\appdata\local\programs\python\python39\include -Ic:\users\john\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /TcC:\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.c /Fobuild\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.obj
    _lupa.c
    C:\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.c(16397): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.c(19375): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.c(21572): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\john\appdata\local\programs\python\python39\libs /LIBPATH:c:\users\john\appdata\local\programs\python\python39\PCbuild\amd64 /LIBPATH:build\temp.win-amd64-3.9 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 lua.lib /EXPORT:PyInit__lupa build\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.obj /OUT:build\lib.win-amd64-3.9\lupa\_lupa.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.cp39-win_amd64.lib
       Creating library build\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.cp39-win_amd64.lib and object build\temp.win-amd64-3.9\Release\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\lupa\_lupa.cp39-win_amd64.exp
    Generating code
    Finished generating code
    running install_lib
    copying build\lib.win-amd64-3.9\lupa\version.py -> c:\users\john\appdata\local\programs\python\python39\Lib\site-packages\lupa
    copying build\lib.win-amd64-3.9\lupa\_lupa.cp39-win_amd64.pyd -> c:\users\john\appdata\local\programs\python\python39\Lib\site-packages\lupa
    byte-compiling c:\users\john\appdata\local\programs\python\python39\Lib\site-packages\lupa\version.py to version.cpython-39.pyc
    running install_egg_info
    running egg_info
    writing lupa.egg-info\PKG-INFO
    writing dependency_links to lupa.egg-info\dependency_links.txt
    writing top-level names to lupa.egg-info\top_level.txt
    reading manifest file 'lupa.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\john\AppData\Local\Temp\pip-install-g4d8qi3j\lupa_2bf72a00acdc4e058108c02363f4ec0c\setup.py", line 353, in <module>
        setup(
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 558, in run
        self.run_command(cmd_name)
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
        self.run_command('egg_info')
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 297, in run
        self.find_sources()
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 304, in find_sources
        mm.run()
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 535, in run
        self.add_defaults()
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 579, in add_defaults
        self.read_manifest()
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\sdist.py", line 220, in read_manifest
        self.filelist.append(line)
      File "c:\users\john\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 477, in append
        path = convert_path(item)
      File "c:\users\john\appdata\local\programs\python\python39\lib\distutils\util.py", line 123, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/home/stefan/source/Python/lua/lupa-release/lupa/_lupa.c' cannot be absolute
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\john\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\john\\AppData\\Local\\Temp\\pip-install-g4d8qi3j\\lupa_2bf72a00acdc4e058108c02363f4ec0c\\setup.py'"'"'; __file__='"'"'C:\\Users\\john\\AppData\\Local\\Temp\\pip-install-g4d8qi3j\\lupa_2bf72a00acdc4e058108c02363f4ec0c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\john\AppData\Local\Temp\pip-record-ib_kvefk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\john\appdata\local\programs\python\python39\Include\lupa' Check the logs for full command output.```

**Comment by maduck** [comment]
in lupa-1.10.tar.gz, `SOURCES.txt` contains this in line 7:
```
/home/stefan/source/Python/lua/lupa-release/lupa/_lupa.c
```
changing it to 
```
lupa/_lupa.c
```
fixes the error for me.

**Comment by scoder** [comment]
Probably resolved in https://github.com/scoder/lupa/commit/aedebd4089b9d1f32fb02075b9c75b844cb972ad
