### ISSUE TITLE
undefined symbol: lua_gettop on python:3.10 docker

### ISSUE THREAD

**Issue by narel** [scoder/lupa#197]
```
$ docker run --rm -it python:3.10 bash
# pip install lupa
# python
>>> import lupa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/lupa/__init__.py", line 32, in <module>
    from lupa._lupa import *
ImportError: /usr/local/lib/python3.10/site-packages/lupa/_lupa.cpython-310-x86_64-linux-gnu.so: undefined symbol: lua_gettop
```

**Comment by scoder** [comment]
Probably resolved in Lupa 1.11.

**Comment by tammoippen** [comment]
I have this in plain ubuntu/pop_os 21.10:

```sh
> uname --all
Linux totem 5.15.23-76051523-generic #202202110435~1644952300~21.10~96763f1 SMP Tue Feb 15 19:52:40 U x86_64 x86_64 x86_64 GNU/Linux
> pip3 install lupa
Collecting lupa
  Downloading lupa-1.11-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_24_x86_64.whl (139 kB)
     |████████████████████████████████| 139 kB 3.8 MB/s
Installing collected packages: lupa
Successfully installed lupa-1.11
> python3 -c 'import lupa'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tammo/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lupa/__init__.py", line 32, in <module>
    from lupa._lupa import *
ImportError: /home/tammo/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lupa/_lupa.cpython-310-x86_64-linux-gnu.so: undefined symbol: lua_gettop
```

**Comment by fzuccolo** [comment]
I'm getting the same error on Ubuntu 20:
```

$ pip3 install lupa --no-cache-dir
Collecting lupa
  Downloading lupa-1.11-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_24_x86_64.whl (139 kB)
     |████████████████████████████████| 139 kB 108 kB/s 
Installing collected packages: lupa
Successfully installed lupa-1.11
$ python -c "import lupa"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.8/site-packages/lupa/__init__.py", line 32, in <module>
    from lupa._lupa import *
ImportError: /tmp/venv/lib/python3.8/site-packages/lupa/_lupa.cpython-38-x86_64-linux-gnu.so: undefined symbol: lua_gettop
```

**Comment by scoder** [comment]
Then probably resolved in Lupa 1.12. :)
https://github.com/scoder/lupa/commit/f79988995db007d046d72aaf167c092b1d65f780

I also added an import test for the wheel to make sure that it was actually built correctly.
https://github.com/scoder/lupa/commit/cdec8e093c825a2316b2fcbf35a6714a539199b8

**Comment by fzuccolo** [comment]
Amazing, thank you!

**Comment by tammoippen** [comment]
Solved for me! Awesome!
