### ISSUE TITLE
RuntimeError: Makefile not found in /home/user/Development/lupa/third-party/lua52/

### ISSUE THREAD

**Issue by BlackMage2** [scoder/lupa#242]
Hello,

i can't compile lupa.
i get ever:
```
$ make
python3 setup.py build_ext --inplace 
Using bundled Lua in lua51
Using bundled Lua in lua52
Traceback (most recent call last):
  File "/home/user/Development/lupa/setup.py", line 358, in <module>
    configs = [
  File "/home/user/Development/lupa/setup.py", line 359, in <listcomp>
    use_bundled_lua(lua_bundle_path, c_defines)
  File "/home/user/Development/lupa/setup.py", line 270, in use_bundled_lua
    raise RuntimeError("Makefile not found in " + path)
RuntimeError: Makefile not found in /home/user/Development/lupa/third-party/lua52/
make: *** [Makefile:25: local] Fehler 1
```

**Comment by scoder** [comment]
If this is from a git checkout, you might just have forgotten to update the git submodules.
The source distribution should be complete.
Closing this since it's probably an issue on user side. Feel free to report back if you think that it wasn't.
