### ISSUE TITLE
Can not used in centos

### ISSUE THREAD

**Issue by XuYunnan** [scoder/lupa#55]
After I install lupa 1.1 by "pip install lupa" in CentOS, I found this error:

```shell
[vagrant@localhost download]$ python
Python 2.7.5 (default, Jun 24 2015, 00:41:19) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lupa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/lupa/__init__.py", line 31, in <module>
    from lupa._lupa import *
ImportError: /usr/lib/python2.7/site-packages/lupa/_lupa.so: undefined symbol: lua_gettop
>>> 
```
Can anyone help me?

**Comment by kmike** [comment]
Could you please share `pip install lupa` log?

**Comment by XuYunnan** [comment]
try again and it works but i don't know why
