### ISSUE TITLE
Error when importing lupa 

### ISSUE THREAD

**Issue by mdtux89** [scoder/lupa#69]
Hi, I installed lupa as explained in INSTALL.rst and it seemed to work. The output of `python setup.py install` is the following:
```
found LuaJIT build in /afs/inf.ed.ac.uk/user/s13/s1333293/lupa-1.2/LuaJIT-2.0.4/src
building statically
building without Cython
running install
running bdist_egg
running egg_info
writing lupa.egg-info/PKG-INFO
writing top-level names to lupa.egg-info/top_level.txt
writing dependency_links to lupa.egg-info/dependency_links.txt
reading manifest file 'lupa.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lupa.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.6
creating build/lib.linux-x86_64-2.6/lupa
copying lupa/version.py -> build/lib.linux-x86_64-2.6/lupa
copying lupa/__init__.py -> build/lib.linux-x86_64-2.6/lupa
running build_ext
building 'lupa._lupa' extension
creating build/temp.linux-x86_64-2.6
creating build/temp.linux-x86_64-2.6/lupa
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLUA_COMPAT_ALL -I/afs/inf.ed.ac.uk/user/s13/s1333293/lupa-1.2/LuaJIT-2.0.4/src -I/usr/include/python2.6 -c lupa/_lupa.c -o build/temp.linux-x86_64-2.6/lupa/_lupa.o
gcc -pthread -shared build/temp.linux-x86_64-2.6/lupa/_lupa.o /afs/inf.ed.ac.uk/user/s13/s1333293/lupa-1.2/LuaJIT-2.0.4/src/libluajit.a -L/usr/lib64 -lpython2.6 -o build/lib.linux-x86_64-2.6/lupa/_lupa.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/lupa
copying build/lib.linux-x86_64-2.6/lupa/version.py -> build/bdist.linux-x86_64/egg/lupa
copying build/lib.linux-x86_64-2.6/lupa/__init__.py -> build/bdist.linux-x86_64/egg/lupa
copying build/lib.linux-x86_64-2.6/lupa/_lupa.so -> build/bdist.linux-x86_64/egg/lupa
byte-compiling build/bdist.linux-x86_64/egg/lupa/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/lupa/__init__.py to __init__.pyc
creating stub loader for lupa/_lupa.so
byte-compiling build/bdist.linux-x86_64/egg/lupa/_lupa.py to _lupa.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying lupa.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lupa.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lupa.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lupa.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying lupa.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/lupa-1.2-py2.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing lupa-1.2-py2.6-linux-x86_64.egg
creating /afs/inf.ed.ac.uk/user/s13/s1333293/virt_env/virt1/lib/python2.6/site-packages/lupa-1.2-py2.6-linux-x86_64.egg
Extracting lupa-1.2-py2.6-linux-x86_64.egg to /afs/inf.ed.ac.uk/user/s13/s1333293/virt_env/virt1/lib/python2.6/site-packages
Adding lupa 1.2 to easy-install.pth file

Installed /afs/inf.ed.ac.uk/user/s13/s1333293/virt_env/virt1/lib/python2.6/site-packages/lupa-1.2-py2.6-linux-x86_64.egg
Processing dependencies for lupa==1.2
Finished processing dependencies for lupa==1.2
```
However, when I tried to import lupa I got the error:
```
>>> import lupa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lupa/__init__.py", line 31, in <module>
    from lupa._lupa import *
ImportError: No module named _lupa
```
I've seen two similar issues on this but they didn't help. The funny thing is that I actually succeeded in installing using lupa a few days ago but I uninstalled it by mistake and now it doesn't seem to work anymore. Any ideas?

Marco

**Comment by kmike** [comment]
Have you by chance fired a Python interpreter while being at lupa source tree? In this case you're trying to import lupa relative to the current dir, not installed lupa, and this fails because it doesn't have the extension built. Try to chdir to another folder - does import work?

**Comment by mdtux89** [comment]
Damn, you're right! Sorry for wasting your time =)

**Comment by kmike** [comment]
No worries, I fell into this trap more than once myself :)
