### ISSUE TITLE
undefined symbol: lua_gettop on CentOS 7

### ISSUE THREAD

**Issue by Jayatubi** [scoder/lupa#86]
I'm trying to install lupa on CentOS 7.

I download the source of Lua 5.2 and build the lib:

````
# nm lib/liblua.a | grep lua_gettop
0000000000000290 T lua_gettop
                 U lua_gettop
                 U lua_gettop
                 U lua_gettop
                 U lua_gettop
                 U lua_gettop
                 U lua_gettop
                 U lua_gettop
                 U lua_gettop
                 U lua_gettop
````

Then I install lupa via pip without errors:

````
Installing collected packages: lupa
  Running setup.py install for lupa ... done
Successfully installed lupa-1.4
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
````

When I was trying to import lupa in python I got such error:

````
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lupa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/lupa/__init__.py", line 31, in <module>
    from lupa._lupa import *
ImportError: /usr/lib64/python2.7/site-packages/lupa/_lupa.so: undefined symbol: lua_gettop
````

More information:

````
~ # nm /usr/lib64/python2.7/site-packages/lupa/_lupa.so | grep lua_gettop                                                         
                 U lua_gettop

~ # ldd /usr/lib64/python2.7/site-packages/lupa/_lupa.so                                                                           
	linux-vdso.so.1 =>  (0x00007ffda6d39000)
	libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f62ac25f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f62ac043000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f62abc80000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f62aba7c000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f62ab879000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f62ab576000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f62ac86f000)
````

It seems the lupa didn't link the function statically or keep a reference to the dynamic lib neither.

**Comment by Jayatubi** [comment]
Found the reason:

If I build the Lua 5.2 from source code it won't be registered into pkg-config thus the setup.py of lupa won't be able to found it.

A, probably bad, walkaround is hardcode the path for my Lua stuffs such as:

````
def find_lua_build(no_luajit=False):

    return dict(
              extra_objects=["/root/lua/lib/liblua.a"],
              include_dirs=["/root/lua/include"]
           )
````

Then I could run `python setup.py install` to make it build and install.

BTW. Before install lupa I need to modify the Lua's make file to add `-fPIC` to CFLAGS.

**Comment by scoder** [comment]
Seems resolved, not a bug in Lupa.
